---
title: "Final Project for SDS Certificate"
author: "Morgan Tucker (mt36459)"
date: "2023-02-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1: Setup
library(tidyverse)
library(sf)
library(raster)

# Read the climate data from an rds file
climate <- readRDS("~/Desktop/ut things/climate_raster.rds")

# Variables
colnames(climate)

# Convert to SpatialPixelDataFrame for plotting
climate_df <- mutate(.data = climate, 
  rasters = map(
    .x = rasters, 
    ~ as_tibble(as(.x, "SpatialPixelsDataFrame")))) %>% unnest(cols = c(rasters))
climate_df
```

```{r}
#2: Maps of the Changing Climate in the UK

# Filter the data to plot, show min temp changes
ggp_temperature_min <- climate_df %>%
  ggplot(aes(x = x, y = y)) + 
  geom_tile(aes(fill = minimum.temperature)) +
  coord_equal() + 
  facet_grid(~ decade) + 
  scale_fill_distiller(palette = "Spectral") + 
  theme(legend.position = "bottom", 
        axis.text = element_blank(), 
        axis.title = element_blank(), 
        axis.ticks = element_blank(),
        text = element_text(family = "Times New Roman")) +
  facet_grid(~ decade) +
  labs(title = "Figure 1. Minimum of Average Monthly Temperature (Celsius)", 
       caption = 'MetOffice UK',
       fill = "Temperature Increase")

ggp_temperature_min


# Filter the data to plot, show max temp changes
ggp_temperature_max <- climate_df %>%
  ggplot(aes(x = x, y = y)) + 
  geom_tile(aes(fill = maximum.temperature)) +
  coord_equal() + 
  facet_grid(~ decade) + 
  scale_fill_distiller(palette = "Spectral") + 
  theme(legend.position = "bottom", 
        axis.text = element_blank(), 
        axis.title = element_blank(), 
        axis.ticks = element_blank(),
        text = element_text(family = "Times New Roman")) +
  facet_grid(~ decade) +
  labs(title = "Figure 2. Maximum of Average Monthly Temperature (Celsius)", 
       caption = 'MetOffice UK',
       fill = "Temperature Increase")

ggp_temperature_max

```


```{r}
#3. Downloading the data

library(rgbif)
source("~/Desktop/ut things/occ_search.R")

# Call the API to get the occurrence records of this species
gbif_response <- occ_search(
  scientificName = "Lophophanes cristatus", country = "GB",
  hasCoordinate = TRUE, hasGeospatialIssue = FALSE, limit = 2000)

# Inspect the class and names of gbif_response
class(gbif_response)
names(gbif_response)

```

```{r}
#4. Cleaning

library(lubridate)

dated <- mutate(
  .data = gbif_response$data,
  decade = ymd_hms(eventDate) %>% round_date("10y") %>% year())

cleaned <- dated %>%
  filter(
    issues == "" &
    str_detect(license, "http://creativecommons.org/") &
    decade >= 1970 & decade <= 2010
  ) %>% transmute(decade = decade, x = decimalLongitude, y = decimalLatitude) %>%
  arrange(decade)

```

```{r}
#5. Nesting

nested <- cleaned %>% 
  group_by(decade) %>% 
  nest(.key = "presences")

counted <- nested %>%
  mutate(n = map_dbl(.x = presences, .f = nrow))

```

```{r}
#6. Spatial Projections

# Defining the geographical projections
projlatlon <- st_crs("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
projukgrid <- st_crs("+init=epsg:27700")

# Converting the records spatially and projecting them
birds_presences <- mutate(counted,
  presences = map(presences, ~ .x %>%
    st_as_sf(coords = c("x", "y"), crs = projlatlon) %>%
    st_transform(crs = projukgrid)))
```

```{r}
#7. Extraction

# Combine the bird data and the climate data
birds_climate <- full_join(birds_presences, climate, by = "decade")
birds_climate

presence_data <- map2_df(
  .x = birds_climate[["rasters"]], .y = birds_climate[["presences"]],
  ~ raster::extract(x=.x, y=.y) %>% 
    as_tibble() %>% mutate(observation = "presence"))

presence_data

```

```{r}
# 8. Pseudo-absences

# Function for creating pseudo-absences
create_pseudo_absences <- function(rasters, n, ...) {
    set.seed(12345)
    sampleRandom(rasters, size = n * 5, sp = TRUE) %>% 
    raster::extract(rasters, .) %>% as_tibble() %>%
    mutate(observation = "pseudo_absence")
}

# Pseudo-absence proportional to the total number of records per decade
pseudo_absence_data <- pmap_df(.l = birds_climate, .f = create_pseudo_absences)

# Combining the datasets
model_data <- bind_rows(presence_data, pseudo_absence_data) %>%
  mutate(observation = factor(observation)) %>% na.omit()
```

```{r}
#9. CARET model
library(caret)
set.seed(1234)

# Tuning grid with sets of hyperparameters (12 combinations)
tuneGrid <- expand.grid(alpha = c(0, 0.5, 1), lambda = c(.003, .01, .03, .06))

# Model training
trControl <- trainControl(method = 'repeatedcv', number = 5, repeats = 1,
  classProbs = TRUE, verboseIter = FALSE, summaryFunction = twoClassSummary)

# Statistical model
model_fit <- train(observation ~ ., data = model_data,
  method = "glmnet", family = "binomial", metric = "ROC",
  tuneGrid = tuneGrid, trControl = trControl)

plot(model_fit)
```

```{r}
#10. Probability of Predictions

climate_df[["prediction"]] <- predict(object = model_fit, new = climate_df,
    type = "prob")[["presence"]]

head(climate_df)
```

```{r}
#11. Final Map on Habitat Suitability
library(viridis)
library(ggthemes)

ggp_changemap <- ggplot(data = climate_df, aes(x = x, y = y, fill = prediction)) +
  geom_tile() + theme_map() + coord_equal() +
  scale_fill_viridis(option = "A") + 
  theme(legend.position = "bottom", 
        legend.justification = "center",
        text = element_text(family = "Times New Roman", size = 11)) +
  facet_grid(~ decade) +
  labs(title = 'Habitat Suitability By Decade',
       caption = 'GBIF and MetOffice UK',
       fill = 'Habitat Suitability\n[0 low - high 1]')

ggp_changemap
```

